name: pathfinder
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  device_info_plus: ^10.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  location: ^6.0.2
  maplibre_gl: ^0.20.0
  maplibre_gl_web: ^0.20.0
  path_provider: ^2.1.4
  build:
  source_gen:
  debug_overlay: ^0.2.12
  flutter_debug_overlay: ^0.1.9
  provider: ^6.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: 
  build_config:

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/data/josm/main.geojson
